# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import dempy.protofiles.base_pb2 as base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='dempy',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0csample.proto\x12\x05\x64\x65mpy\x1a\nbase.proto\"\xbc\x01\n\x10TimeseriesSample\x12\x1d\n\x06\x65ntity\x18\x01 \x02(\x0b\x32\r.dempy.Entity\x12\x14\n\ttimestamp\x18\x02 \x02(\x03:\x01\x30\x12\x16\n\x0e\x61\x63quisition_id\x18\x03 \x02(\t\x12\x11\n\tdevice_id\x18\x04 \x01(\t\x12\x11\n\tsensor_id\x18\x05 \x01(\t\x12\t\n\x01x\x18\x06 \x01(\x02\x12\t\n\x01y\x18\x07 \x01(\x02\x12\t\n\x01z\x18\x08 \x01(\x02\x12\t\n\x01u\x18\t \x01(\x02\x12\t\n\x01w\x18\n \x01(\x02\"\xc9\x01\n\x0bImageSample\x12\x1d\n\x06\x65ntity\x18\x01 \x02(\x0b\x32\r.dempy.Entity\x12\x14\n\ttimestamp\x18\x02 \x02(\x03:\x01\x30\x12\x16\n\x0e\x61\x63quisition_id\x18\x03 \x02(\t\x12\x11\n\tdevice_id\x18\x04 \x01(\t\x12\x11\n\tsensor_id\x18\x05 \x01(\t\x12\x12\n\nmedia_type\x18\x06 \x02(\t\x12\x14\n\x0cimage_source\x18\x07 \x02(\t\x12\x1d\n\x15has_rotation_metadata\x18\x08 \x02(\x08\"\xaa\x01\n\x0bVideoSample\x12\x1d\n\x06\x65ntity\x18\x01 \x02(\x0b\x32\r.dempy.Entity\x12\x14\n\ttimestamp\x18\x02 \x02(\x03:\x01\x30\x12\x16\n\x0e\x61\x63quisition_id\x18\x03 \x02(\t\x12\x11\n\tdevice_id\x18\x04 \x01(\t\x12\x11\n\tsensor_id\x18\x05 \x01(\t\x12\x12\n\nmedia_type\x18\x06 \x02(\t\x12\x14\n\x0cvideo_source\x18\x07 \x02(\t'
  ,
  dependencies=[base__pb2.DESCRIPTOR,])




_TIMESERIESSAMPLE = _descriptor.Descriptor(
  name='TimeseriesSample',
  full_name='dempy.TimeseriesSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity', full_name='dempy.TimeseriesSample.entity', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='dempy.TimeseriesSample.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acquisition_id', full_name='dempy.TimeseriesSample.acquisition_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='dempy.TimeseriesSample.device_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='dempy.TimeseriesSample.sensor_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='dempy.TimeseriesSample.x', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='dempy.TimeseriesSample.y', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='dempy.TimeseriesSample.z', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='u', full_name='dempy.TimeseriesSample.u', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='dempy.TimeseriesSample.w', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=224,
)


_IMAGESAMPLE = _descriptor.Descriptor(
  name='ImageSample',
  full_name='dempy.ImageSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity', full_name='dempy.ImageSample.entity', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='dempy.ImageSample.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acquisition_id', full_name='dempy.ImageSample.acquisition_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='dempy.ImageSample.device_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='dempy.ImageSample.sensor_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='media_type', full_name='dempy.ImageSample.media_type', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_source', full_name='dempy.ImageSample.image_source', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_rotation_metadata', full_name='dempy.ImageSample.has_rotation_metadata', index=7,
      number=8, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=428,
)


_VIDEOSAMPLE = _descriptor.Descriptor(
  name='VideoSample',
  full_name='dempy.VideoSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity', full_name='dempy.VideoSample.entity', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='dempy.VideoSample.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acquisition_id', full_name='dempy.VideoSample.acquisition_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='dempy.VideoSample.device_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='dempy.VideoSample.sensor_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='media_type', full_name='dempy.VideoSample.media_type', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_source', full_name='dempy.VideoSample.video_source', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=601,
)

_TIMESERIESSAMPLE.fields_by_name['entity'].message_type = base__pb2._ENTITY
_IMAGESAMPLE.fields_by_name['entity'].message_type = base__pb2._ENTITY
_VIDEOSAMPLE.fields_by_name['entity'].message_type = base__pb2._ENTITY
DESCRIPTOR.message_types_by_name['TimeseriesSample'] = _TIMESERIESSAMPLE
DESCRIPTOR.message_types_by_name['ImageSample'] = _IMAGESAMPLE
DESCRIPTOR.message_types_by_name['VideoSample'] = _VIDEOSAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeseriesSample = _reflection.GeneratedProtocolMessageType('TimeseriesSample', (_message.Message,), {
  'DESCRIPTOR' : _TIMESERIESSAMPLE,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:dempy.TimeseriesSample)
  })
_sym_db.RegisterMessage(TimeseriesSample)

ImageSample = _reflection.GeneratedProtocolMessageType('ImageSample', (_message.Message,), {
  'DESCRIPTOR' : _IMAGESAMPLE,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:dempy.ImageSample)
  })
_sym_db.RegisterMessage(ImageSample)

VideoSample = _reflection.GeneratedProtocolMessageType('VideoSample', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOSAMPLE,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:dempy.VideoSample)
  })
_sym_db.RegisterMessage(VideoSample)


# @@protoc_insertion_point(module_scope)
