# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: util.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import dempy.protofiles.sample_pb2 as sample__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='util.proto',
  package='dempy',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\nutil.proto\x12\x05\x64\x65mpy\x1a\x0csample.proto\"\x81\x01\n\nSampleList\x12+\n\ntimeseries\x18\x01 \x03(\x0b\x32\x17.dempy.TimeseriesSample\x12\"\n\x06images\x18\x02 \x03(\x0b\x32\x12.dempy.ImageSample\x12\"\n\x06videos\x18\x03 \x03(\x0b\x32\x12.dempy.VideoSample'
  ,
  dependencies=[sample__pb2.DESCRIPTOR,])




_SAMPLELIST = _descriptor.Descriptor(
  name='SampleList',
  full_name='dempy.SampleList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeseries', full_name='dempy.SampleList.timeseries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='dempy.SampleList.images', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='videos', full_name='dempy.SampleList.videos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=165,
)

_SAMPLELIST.fields_by_name['timeseries'].message_type = sample__pb2._TIMESERIESSAMPLE
_SAMPLELIST.fields_by_name['images'].message_type = sample__pb2._IMAGESAMPLE
_SAMPLELIST.fields_by_name['videos'].message_type = sample__pb2._VIDEOSAMPLE
DESCRIPTOR.message_types_by_name['SampleList'] = _SAMPLELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SampleList = _reflection.GeneratedProtocolMessageType('SampleList', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLELIST,
  '__module__' : 'util_pb2'
  # @@protoc_insertion_point(class_scope:dempy.SampleList)
  })
_sym_db.RegisterMessage(SampleList)


# @@protoc_insertion_point(module_scope)
